-- Seed the open-source hairstyle reference gallery from files tracked in public/styles.
-- Keep image_url values aligned with public/styles/*.png so self-hosted installs have
-- a populated gallery without relying on external image hosts.

INSERT INTO public.style_gallery (
  name,
  image_url,
  category,
  gender,
  hair_length,
  tags,
  compatible_face_shapes,
  compatible_hair_types,
  compatible_hair_thicknesses
)
SELECT
  seed.name,
  seed.image_url,
  seed.category,
  seed.gender,
  seed.hair_length,
  seed.tags,
  ARRAY['oval', 'round', 'square', 'heart', 'oblong', 'diamond', 'triangle', 'inverted_triangle']::public.face_shape[],
  ARRAY['straight', 'wavy', 'curly', 'coily']::text[],
  ARRAY['fine', 'medium', 'thick']::text[]
FROM (VALUES
  ('A Line Bob', '/styles/a-line-bob.png', 'Bobs', 'female', 'short', ARRAY['bobs', 'female']::text[]),
  ('Afro', '/styles/afro-male.png', 'Texture', 'male', 'medium', ARRAY['texture', 'male']::text[]),
  ('Angular Fringe', '/styles/angular-fringe.png', 'Bangs', 'unisex', 'medium', ARRAY['bangs', 'unisex']::text[]),
  ('Asymmetrical Bob', '/styles/asymmetrical-bob.png', 'Bobs', 'female', 'short', ARRAY['bobs', 'female']::text[]),
  ('Asymmetrical Pixie', '/styles/asymmetrical-pixie.png', 'Short', 'female', 'short', ARRAY['short', 'female']::text[]),
  ('Bantu Knots', '/styles/bantu-knots.png', 'Protective', 'unisex', 'medium', ARRAY['protective', 'unisex']::text[]),
  ('Bardot Bangs', '/styles/bardot-bangs.png', 'Bangs', 'female', 'medium', ARRAY['bangs', 'female']::text[]),
  ('Beach Waves', '/styles/beach-waves.png', 'Texture', 'female', 'medium', ARRAY['texture', 'female']::text[]),
  ('Birkin Bangs', '/styles/birkin-bangs.png', 'Bangs', 'female', 'medium', ARRAY['bangs', 'female']::text[]),
  ('Bixie', '/styles/bixie.png', 'Reference', 'unisex', 'medium', ARRAY['reference', 'unisex']::text[]),
  ('Blowout', '/styles/blowout-female.png', 'Reference', 'female', 'medium', ARRAY['reference', 'female']::text[]),
  ('Blowout', '/styles/blowout-male.png', 'Reference', 'male', 'medium', ARRAY['reference', 'male']::text[]),
  ('Blunt Bangs', '/styles/blunt-bangs.png', 'Bangs', 'female', 'medium', ARRAY['bangs', 'female']::text[]),
  ('Blunt Bob', '/styles/blunt-bob.png', 'Bobs', 'female', 'short', ARRAY['bobs', 'female']::text[]),
  ('Blunt Cut', '/styles/blunt-cut.png', 'Reference', 'female', 'medium', ARRAY['reference', 'female']::text[]),
  ('Bottleneck Bangs', '/styles/bottleneck-bangs.png', 'Bangs', 'female', 'medium', ARRAY['bangs', 'female']::text[]),
  ('Box Braids', '/styles/box-braids-female.png', 'Braids', 'female', 'medium', ARRAY['braids', 'female']::text[]),
  ('Box Braids', '/styles/box-braids.png', 'Braids', 'female', 'medium', ARRAY['braids', 'female']::text[]),
  ('Braids Cornrows', '/styles/braids-cornrows.png', 'Braids', 'female', 'medium', ARRAY['braids', 'female']::text[]),
  ('Bro Flow', '/styles/bro-flow.png', 'Reference', 'unisex', 'medium', ARRAY['reference', 'unisex']::text[]),
  ('Burst Fade', '/styles/burst-fade.png', 'Fades', 'male', 'short', ARRAY['fades', 'male']::text[]),
  ('Business Cut', '/styles/business-cut.png', 'Classic', 'male', 'short', ARRAY['classic', 'male']::text[]),
  ('Butterfly Cut', '/styles/butterfly-cut.png', 'Layered', 'female', 'medium', ARRAY['layered', 'female']::text[]),
  ('Buzz Cut', '/styles/buzz-cut-female.png', 'Short', 'female', 'short', ARRAY['short', 'female']::text[]),
  ('Buzz Cut', '/styles/buzz-cut.png', 'Short', 'male', 'short', ARRAY['short', 'male']::text[]),
  ('Caesar Cut', '/styles/caesar-cut.png', 'Short', 'male', 'short', ARRAY['short', 'male']::text[]),
  ('Choppy Bob', '/styles/choppy-bob.png', 'Bobs', 'female', 'short', ARRAY['bobs', 'female']::text[]),
  ('Classic Bob', '/styles/classic-bob.png', 'Bobs', 'female', 'short', ARRAY['bobs', 'female']::text[]),
  ('Classic Fade', '/styles/classic-fade.png', 'Fades', 'male', 'short', ARRAY['fades', 'male']::text[]),
  ('Claw Clip Updo', '/styles/claw-clip-updo.png', 'Updos', 'unisex', 'medium', ARRAY['updos', 'unisex']::text[]),
  ('Collarbone Cut', '/styles/collarbone-cut.png', 'Reference', 'female', 'medium', ARRAY['reference', 'female']::text[]),
  ('Comb Over Fade', '/styles/comb-over-fade.png', 'Fades', 'male', 'short', ARRAY['fades', 'male']::text[]),
  ('Comb Over', '/styles/comb-over.png', 'Classic', 'male', 'medium', ARRAY['classic', 'male']::text[]),
  ('Cornrows', '/styles/cornrows-female.png', 'Braids', 'female', 'medium', ARRAY['braids', 'female']::text[]),
  ('Crew Cut', '/styles/crew-cut.png', 'Short', 'male', 'short', ARRAY['short', 'male']::text[]),
  ('Curtain Bangs', '/styles/curtain-bangs-female.png', 'Bangs', 'female', 'medium', ARRAY['bangs', 'female']::text[]),
  ('Curtain Bangs', '/styles/curtain-bangs.png', 'Bangs', 'female', 'medium', ARRAY['bangs', 'female']::text[]),
  ('Curtain Cut', '/styles/curtain-cut.png', 'Classic', 'male', 'medium', ARRAY['classic', 'male']::text[]),
  ('Curtain Layers', '/styles/curtain-layers.png', 'Layered', 'female', 'medium', ARRAY['layered', 'female']::text[]),
  ('Defined Curls', '/styles/defined-curls.png', 'Texture', 'female', 'medium', ARRAY['texture', 'female']::text[]),
  ('Disconnected Undercut', '/styles/disconnected-undercut.png', 'Edgy', 'male', 'medium', ARRAY['edgy', 'male']::text[]),
  ('Drop Fade', '/styles/drop-fade.png', 'Fades', 'male', 'short', ARRAY['fades', 'male']::text[]),
  ('Edgar Cut', '/styles/edgar-cut.png', 'Short', 'male', 'medium', ARRAY['short', 'male']::text[]),
  ('Face Framing Layers', '/styles/face-framing-layers.png', 'Layered', 'female', 'medium', ARRAY['layered', 'female']::text[]),
  ('Farrah Fawcett Flip', '/styles/farrah-fawcett-flip.png', 'Reference', 'unisex', 'medium', ARRAY['reference', 'unisex']::text[]),
  ('Faux Hawk', '/styles/faux-hawk.png', 'Edgy', 'male', 'medium', ARRAY['edgy', 'male']::text[]),
  ('Faux Locs', '/styles/faux-locs.png', 'Protective', 'female', 'medium', ARRAY['protective', 'female']::text[]),
  ('Feathered Layers', '/styles/feathered-layers.png', 'Layered', 'female', 'medium', ARRAY['layered', 'female']::text[]),
  ('Feed In Braids', '/styles/feed-in-braids.png', 'Braids', 'female', 'medium', ARRAY['braids', 'female']::text[]),
  ('Flat Top', '/styles/flat-top.png', 'Reference', 'male', 'medium', ARRAY['reference', 'male']::text[]),
  ('Flat Twists', '/styles/flat-twists.png', 'Protective', 'female', 'medium', ARRAY['protective', 'female']::text[]),
  ('French Bob', '/styles/french-bob.png', 'Bobs', 'female', 'short', ARRAY['bobs', 'female']::text[]),
  ('French Crop', '/styles/french-crop.png', 'Short', 'male', 'short', ARRAY['short', 'male']::text[]),
  ('French Twist', '/styles/french-twist.png', 'Protective', 'female', 'medium', ARRAY['protective', 'female']::text[]),
  ('Fulani Braids', '/styles/fulani-braids.png', 'Braids', 'female', 'medium', ARRAY['braids', 'female']::text[]),
  ('Glass Hair Bob', '/styles/glass-hair-bob.png', 'Bobs', 'female', 'short', ARRAY['bobs', 'female']::text[]),
  ('Goddess Braids', '/styles/goddess-braids.png', 'Braids', 'female', 'medium', ARRAY['braids', 'female']::text[]),
  ('Hard Part', '/styles/hard-part.png', 'Classic', 'male', 'short', ARRAY['classic', 'male']::text[]),
  ('High Top Fade', '/styles/high-top-fade.png', 'Fades', 'male', 'short', ARRAY['fades', 'male']::text[]),
  ('Hime Cut', '/styles/hime-cut.png', 'Reference', 'female', 'medium', ARRAY['reference', 'female']::text[]),
  ('Hollywood Waves', '/styles/hollywood-waves.png', 'Texture', 'female', 'medium', ARRAY['texture', 'female']::text[]),
  ('Inverted Bob', '/styles/inverted-bob.png', 'Bobs', 'female', 'short', ARRAY['bobs', 'female']::text[]),
  ('Italian Bob', '/styles/italian-bob.png', 'Bobs', 'female', 'short', ARRAY['bobs', 'female']::text[]),
  ('Ivy League', '/styles/ivy-league.png', 'Reference', 'male', 'medium', ARRAY['reference', 'male']::text[]),
  ('Jellyfish Cut', '/styles/jellyfish-cut.png', 'Reference', 'female', 'medium', ARRAY['reference', 'female']::text[]),
  ('Knotless Braids', '/styles/knotless-braids.png', 'Braids', 'female', 'medium', ARRAY['braids', 'female']::text[]),
  ('Korean Perm', '/styles/korean-perm.png', 'Reference', 'unisex', 'medium', ARRAY['reference', 'unisex']::text[]),
  ('Layered Lob', '/styles/layered-lob.png', 'Bobs', 'female', 'medium', ARRAY['bobs', 'female']::text[]),
  ('Layered Medium', '/styles/layered-medium.png', 'Layered', 'unisex', 'medium', ARRAY['layered', 'unisex']::text[]),
  ('Line Up', '/styles/line-up.png', 'Reference', 'male', 'medium', ARRAY['reference', 'male']::text[]),
  ('Lob', '/styles/lob.png', 'Bobs', 'female', 'medium', ARRAY['bobs', 'female']::text[]),
  ('Long Pixie', '/styles/long-pixie.png', 'Short', 'female', 'short', ARRAY['short', 'female']::text[]),
  ('Loose Waves', '/styles/loose-waves.png', 'Texture', 'female', 'medium', ARRAY['texture', 'female']::text[]),
  ('Low Bun', '/styles/low-bun.png', 'Updos', 'female', 'medium', ARRAY['updos', 'female']::text[]),
  ('Man Bun', '/styles/man-bun.png', 'Updos', 'male', 'long', ARRAY['updos', 'male']::text[]),
  ('Mermaid Waves', '/styles/mermaid-waves.png', 'Texture', 'female', 'long', ARRAY['texture', 'female']::text[]),
  ('Messy Bun', '/styles/messy-bun.png', 'Updos', 'female', 'medium', ARRAY['updos', 'female']::text[]),
  ('Messy Fringe', '/styles/messy-fringe.png', 'Bangs', 'unisex', 'medium', ARRAY['bangs', 'unisex']::text[]),
  ('Micro Bob', '/styles/micro-bob.png', 'Bobs', 'female', 'short', ARRAY['bobs', 'female']::text[]),
  ('Middle Part', '/styles/middle-part.png', 'Classic', 'unisex', 'medium', ARRAY['classic', 'unisex']::text[]),
  ('Mixie', '/styles/mixie.png', 'Reference', 'unisex', 'medium', ARRAY['reference', 'unisex']::text[]),
  ('Modern Bob', '/styles/modern-bob.png', 'Bobs', 'female', 'short', ARRAY['bobs', 'female']::text[]),
  ('Modern Mullet', '/styles/modern-mullet-female.png', 'Layered', 'female', 'medium', ARRAY['layered', 'female']::text[]),
  ('Modern Mullet', '/styles/modern-mullet-male.png', 'Layered', 'male', 'medium', ARRAY['layered', 'male']::text[]),
  ('Modern Pompadour', '/styles/modern-pompadour.png', 'Classic', 'male', 'medium', ARRAY['classic', 'male']::text[]),
  ('Modern Shag', '/styles/modern-shag.png', 'Layered', 'unisex', 'medium', ARRAY['layered', 'unisex']::text[]),
  ('Mohawk', '/styles/mohawk.png', 'Edgy', 'unisex', 'medium', ARRAY['edgy', 'unisex']::text[]),
  ('Natural Afro', '/styles/natural-afro-female.png', 'Texture', 'female', 'medium', ARRAY['texture', 'female']::text[]),
  ('Octopus Cut', '/styles/octopus-cut.png', 'Reference', 'female', 'medium', ARRAY['reference', 'female']::text[]),
  ('Passion Twists', '/styles/passion-twists.png', 'Protective', 'female', 'medium', ARRAY['protective', 'female']::text[]),
  ('Pixie Cut', '/styles/pixie-cut.png', 'Short', 'female', 'short', ARRAY['short', 'female']::text[]),
  ('Pixie With Bangs', '/styles/pixie-with-bangs.png', 'Bangs', 'female', 'short', ARRAY['bangs', 'female']::text[]),
  ('Pompadour', '/styles/pompadour.png', 'Classic', 'male', 'medium', ARRAY['classic', 'male']::text[]),
  ('Pushed Back Waves', '/styles/pushed-back-waves.png', 'Texture', 'female', 'medium', ARRAY['texture', 'female']::text[]),
  ('Quiff', '/styles/quiff.png', 'Classic', 'male', 'medium', ARRAY['classic', 'male']::text[]),
  ('Rachel Cut', '/styles/rachel-cut.png', 'Reference', 'female', 'medium', ARRAY['reference', 'female']::text[]),
  ('Razor Cut Layers', '/styles/razor-cut-layers.png', 'Layered', 'female', 'medium', ARRAY['layered', 'female']::text[]),
  ('Samurai Bun', '/styles/samurai-bun.png', 'Updos', 'male', 'long', ARRAY['updos', 'male']::text[]),
  ('Senegalese Twists', '/styles/senegalese-twists.png', 'Protective', 'female', 'medium', ARRAY['protective', 'female']::text[]),
  ('Shag Cut', '/styles/shag-cut.png', 'Layered', 'female', 'medium', ARRAY['layered', 'female']::text[]),
  ('Shag', '/styles/shag.png', 'Layered', 'unisex', 'medium', ARRAY['layered', 'unisex']::text[]),
  ('Shaggy Bob', '/styles/shaggy-bob.png', 'Bobs', 'female', 'medium', ARRAY['bobs', 'female']::text[]),
  ('Side Part', '/styles/side-part.png', 'Classic', 'unisex', 'medium', ARRAY['classic', 'unisex']::text[]),
  ('Side Shave', '/styles/side-shave.png', 'Edgy', 'unisex', 'medium', ARRAY['edgy', 'unisex']::text[]),
  ('Side Swept Bangs', '/styles/side-swept-bangs.png', 'Bangs', 'female', 'medium', ARRAY['bangs', 'female']::text[]),
  ('Skin Fade', '/styles/skin-fade.png', 'Fades', 'male', 'short', ARRAY['fades', 'male']::text[]),
  ('Sleek Straight', '/styles/sleek-straight.png', 'Reference', 'unisex', 'medium', ARRAY['reference', 'unisex']::text[]),
  ('Slick Back', '/styles/slick-back.png', 'Classic', 'unisex', 'medium', ARRAY['classic', 'unisex']::text[]),
  ('Slicked Back', '/styles/slicked-back-female.png', 'Classic', 'female', 'medium', ARRAY['classic', 'female']::text[]),
  ('Soft Curls', '/styles/soft-curls.png', 'Texture', 'female', 'medium', ARRAY['texture', 'female']::text[]),
  ('Space Buns', '/styles/space-buns.png', 'Updos', 'female', 'medium', ARRAY['updos', 'female']::text[]),
  ('Spiky Hair', '/styles/spiky-hair.png', 'Short', 'male', 'short', ARRAY['short', 'male']::text[]),
  ('Stacked Bob', '/styles/stacked-bob.png', 'Bobs', 'female', 'short', ARRAY['bobs', 'female']::text[]),
  ('Surfer Hair', '/styles/surfer-hair.png', 'Reference', 'male', 'medium', ARRAY['reference', 'male']::text[]),
  ('Taper Fade', '/styles/taper-fade.png', 'Fades', 'male', 'short', ARRAY['fades', 'male']::text[]),
  ('Taper', '/styles/taper.png', 'Reference', 'male', 'medium', ARRAY['reference', 'male']::text[]),
  ('Tapered Afro', '/styles/tapered-afro.png', 'Texture', 'unisex', 'medium', ARRAY['texture', 'unisex']::text[]),
  ('Temple Fade', '/styles/temple-fade.png', 'Fades', 'male', 'short', ARRAY['fades', 'male']::text[]),
  ('Textured Bob', '/styles/textured-bob.png', 'Bobs', 'female', 'short', ARRAY['bobs', 'female']::text[]),
  ('Textured Crop', '/styles/textured-crop.png', 'Short', 'male', 'short', ARRAY['short', 'male']::text[]),
  ('Textured Pixie', '/styles/textured-pixie.png', 'Short', 'female', 'short', ARRAY['short', 'female']::text[]),
  ('Textured Quiff', '/styles/textured-quiff.png', 'Classic', 'male', 'medium', ARRAY['classic', 'male']::text[]),
  ('Textured Side Sweep', '/styles/textured-side-sweep.png', 'Reference', 'unisex', 'medium', ARRAY['reference', 'unisex']::text[]),
  ('Top Knot', '/styles/top-knot-female.png', 'Updos', 'female', 'medium', ARRAY['updos', 'female']::text[]),
  ('Top Knot', '/styles/top-knot-male.png', 'Updos', 'male', 'medium', ARRAY['updos', 'male']::text[]),
  ('Tousled Waves', '/styles/tousled-waves.png', 'Texture', 'female', 'medium', ARRAY['texture', 'female']::text[]),
  ('Twist Out', '/styles/twist-out-female.png', 'Protective', 'female', 'medium', ARRAY['protective', 'female']::text[]),
  ('Twist Out', '/styles/twist-out-male.png', 'Protective', 'male', 'medium', ARRAY['protective', 'male']::text[]),
  ('Two Block Cut', '/styles/two-block-cut.png', 'Classic', 'male', 'short', ARRAY['classic', 'male']::text[]),
  ('U Cut', '/styles/u-cut.png', 'Reference', 'female', 'long', ARRAY['reference', 'female']::text[]),
  ('Undercut', '/styles/undercut-female.png', 'Edgy', 'female', 'medium', ARRAY['edgy', 'female']::text[]),
  ('Undercut', '/styles/undercut.png', 'Edgy', 'male', 'medium', ARRAY['edgy', 'male']::text[]),
  ('V Cut', '/styles/v-cut.png', 'Reference', 'female', 'long', ARRAY['reference', 'female']::text[]),
  ('Wet Look', '/styles/wet-look.png', 'Reference', 'unisex', 'medium', ARRAY['reference', 'unisex']::text[]),
  ('Wispy Bangs', '/styles/wispy-bangs.png', 'Bangs', 'female', 'medium', ARRAY['bangs', 'female']::text[]),
  ('Wolf Cut', '/styles/wolf-cut-male.png', 'Layered', 'male', 'medium', ARRAY['layered', 'male']::text[]),
  ('Wolf Cut', '/styles/wolf-cut.png', 'Layered', 'female', 'medium', ARRAY['layered', 'female']::text[])
) AS seed(name, image_url, category, gender, hair_length, tags)
WHERE NOT EXISTS (
  SELECT 1
  FROM public.style_gallery existing
  WHERE existing.image_url = seed.image_url
);
