UPDATE style_gallery SET image_url = '/placeholder.svg' WHERE name = 'Afro';
UPDATE style_gallery SET image_url = '/placeholder.svg' WHERE name = 'Angular Fringe';
UPDATE style_gallery SET image_url = '/placeholder.svg' WHERE name = 'Blowout' AND gender = 'male';
UPDATE style_gallery SET image_url = '/placeholder.svg' WHERE name = 'Braids / Cornrows';
UPDATE style_gallery SET image_url = '/placeholder.svg' WHERE name = 'Burst Fade';
UPDATE style_gallery SET image_url = '/placeholder.svg' WHERE name = 'Business Cut';
UPDATE style_gallery SET image_url = '/placeholder.svg' WHERE name = 'Caesar Cut';
UPDATE style_gallery SET image_url = '/placeholder.svg' WHERE name = 'Edgar Cut';
UPDATE style_gallery SET image_url = '/placeholder.svg' WHERE name = 'Flat Top';
UPDATE style_gallery SET image_url = '/placeholder.svg' WHERE name = 'High Top Fade';
UPDATE style_gallery SET image_url = '/placeholder.svg' WHERE name = 'Ivy League';
UPDATE style_gallery SET image_url = '/placeholder.svg' WHERE name = 'Korean Perm';
UPDATE style_gallery SET image_url = '/placeholder.svg' WHERE name = 'Layered Medium Length';
UPDATE style_gallery SET image_url = '/placeholder.svg' WHERE name = 'Line Up';
UPDATE style_gallery SET image_url = '/placeholder.svg' WHERE name = 'Man Bun';
UPDATE style_gallery SET image_url = '/placeholder.svg' WHERE name = 'Modern Mullet' AND gender = 'male';
UPDATE style_gallery SET image_url = '/placeholder.svg' WHERE name = 'Pushed Back Waves';
UPDATE style_gallery SET image_url = '/placeholder.svg' WHERE name = 'Samurai Bun';
UPDATE style_gallery SET image_url = '/placeholder.svg' WHERE name = 'Spiky Hair';
UPDATE style_gallery SET image_url = '/placeholder.svg' WHERE name = 'Surfer Hair';
UPDATE style_gallery SET image_url = '/placeholder.svg' WHERE name = 'Taper';
UPDATE style_gallery SET image_url = '/placeholder.svg' WHERE name = 'Temple Fade';
UPDATE style_gallery SET image_url = '/placeholder.svg' WHERE name = 'Textured Side Sweep';
UPDATE style_gallery SET image_url = '/placeholder.svg' WHERE name = 'Top Knot' AND gender = 'male';
UPDATE style_gallery SET image_url = '/placeholder.svg' WHERE name = 'Tousled Waves';
UPDATE style_gallery SET image_url = '/placeholder.svg' WHERE name = 'Twist Out' AND gender = 'male';
UPDATE style_gallery SET image_url = '/placeholder.svg' WHERE name = 'Two Block Cut';
UPDATE style_gallery SET image_url = '/placeholder.svg' WHERE name = 'Wolf Cut' AND gender = 'male';